services:
  api:
    build: ./api
    container_name: products-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: products-mongo
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: products-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
