services:
  api:
    build: ./app
    container_name: tasks-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: tasks-mongo
    # environment:
    #   - TZ=America/La_Paz
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
