services:
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    container_name: backend-api
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
